export const rows = [
  {
    id: 1,
    name: "Ahmed",
    email: "ahmed@gmail.com",
    age: "20",
    phone: "(442)555-6235",
    access: "Admin",
  },
  {
    id: 2,
    name: "Sara",
    email: "sara@gmail.com",
    age: "25",
    phone: "(442)555-1234",
    access: "User",
  },
  {
    id: 3,
    name: "John",
    email: "john@gmail.com",
    age: "30",
    phone: "(442)555-5678",
    access: "User",
  },
  {
    id: 4,
    name: "Mary",
    email: "mary@gmail.com",
    age: "22",
    phone: "(442)555-9012",
    access: "Manager",
  },
  {
    id: 5,
    name: "Ali",
    email: "ali@gmail.com",
    age: "28",
    phone: "(442)555-3456",
    access: "User",
  },
  {
    id: 6,
    name: "David",
    email: "david@gmail.com",
    age: "35",
    phone: "(442)555-7890",
    access: "Admin",
  },
  {
    id: 7,
    name: "Amina",
    email: "amina@gmail.com",
    age: "27",
    phone: "(442)555-2345",
    access: "User",
  },
  {
    id: 8,
    name: "Omar",
    email: "omar@gmail.com",
    age: "29",
    phone: "(442)555-6789",
    access: "Manager",
  },
  {
    id: 9,
    name: "Fatima",
    email: "fatima@gmail.com",
    age: "24",
    phone: "(442)555-1122",
    access: "User",
  },
  {
    id: 10,
    name: "Youssef",
    email: "youssef@gmail.com",
    age: "32",
    phone: "(442)555-3344",
    access: "Admin",
  },
];
